---
script: rake

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx
  - rbx-head
  - jruby
  - jruby-head
  - jruby-1.7.4

notifications:
  email:
    recipients:
      - development@olery.com
    email:
      on_success: change
      on_failure: always

branches:
  only:
    - master
